// Builds the WebView bridge bundle and stages the Cerbos embedded PDP assets into the Android library.
//
//   npm run build
//
// Outputs (committed to the repo so the Gradle project builds without Node installed):
//   ../cerbos-embedded-pdp/src/main/assets/cerbos-epdp/index.html
//   ../cerbos-embedded-pdp/src/main/assets/cerbos-epdp/bridge.js
//   ../cerbos-embedded-pdp/src/main/assets/cerbos-epdp/server.wasm
//   ../cerbos-embedded-pdp/src/main/assets/cerbos-epdp/manifest.json
import { build } from "esbuild";
import { createHash } from "node:crypto";
import { copyFile, mkdir, readFile, stat, writeFile } from "node:fs/promises";
import { createRequire } from "node:module";
import path from "node:path";
import { fileURLToPath } from "node:url";

const require = createRequire(import.meta.url);
const here = path.dirname(fileURLToPath(import.meta.url));
const outDir = path.resolve(here, "..", "cerbos-embedded-pdp", "src", "main", "assets", "cerbos-epdp");

// Package manifests are not on the packages' export maps, so read them from node_modules directly.
const packageJSON = async (name) => JSON.parse(await readFile(path.join(here, "node_modules", name, "package.json"), "utf8"));
const packageVersion = async (name) => (await packageJSON(name)).version;
const wasmSource = require.resolve("@cerbos/embedded-server/server.wasm");
const serverPackageDir = path.dirname(path.dirname(wasmSource));
const serverMetadata = JSON.parse(await readFile(path.join(serverPackageDir, "src", "metadata.json"), "utf8"));

await mkdir(outDir, { recursive: true });

// 1. Verify and copy the WebAssembly module, checking it against the checksum published by Cerbos.
const wasmBytes = await readFile(wasmSource);
const wasmSHA256 = createHash("sha256").update(wasmBytes).digest("hex");
if (serverMetadata.wasmChecksum && serverMetadata.wasmChecksum !== wasmSHA256) {
  throw new Error(`server.wasm checksum mismatch: expected ${serverMetadata.wasmChecksum}, got ${wasmSHA256}`);
}
await copyFile(wasmSource, path.join(outDir, "server.wasm"));

// 2. Bundle the bridge (IIFE, no external requests: everything the page needs is local).
const versions = {
  "@cerbos/embedded-client": await packageVersion("@cerbos/embedded-client"),
  "@cerbos/embedded-server": await packageVersion("@cerbos/embedded-server"),
  "@cerbos/core": await packageVersion("@cerbos/core"),
  "@cerbos/api": await packageVersion("@cerbos/api"),
};
await build({
  entryPoints: [path.join(here, "src", "bridge.ts")],
  outfile: path.join(outDir, "bridge.js"),
  bundle: true,
  format: "iife",
  platform: "browser",
  // Android System WebView is evergreen Chromium; this floor matches the WebView shipped with Android 8 (API 26).
  target: ["chrome80"],
  minify: true,
  sourcemap: false,
  legalComments: "none",
  define: { "process.env.NODE_ENV": '"production"' },
  banner: {
    js: `/* Cerbos embedded PDP bridge for Android. Generated by CerbosBridge/build.mjs from ${Object.entries(versions).map(([k, v]) => `${k}@${v}`).join(", ")}. Do not edit. */`,
  },
});

// 3. Minimal host page. The bridge script and the WASM are fetched from the same intercepted https origin.
await writeFile(
  path.join(outDir, "index.html"),
  `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'self' 'wasm-unsafe-eval'; connect-src 'self' https: http://localhost:* http://127.0.0.1:*; base-uri 'none'; form-action 'none'">
<title>Cerbos embedded PDP</title>
</head>
<body>
<script src="bridge.js"></script>
</body>
</html>
`,
);

// 4. Manifest consumed by the Kotlin side (versions, checksum) and by humans reviewing upgrades.
// Deliberately free of timestamps so that a rebuild from the same inputs is byte-identical and CI
// can detect a stale or hand-edited manifest with `git diff --exit-code`.
const bridgeStat = await stat(path.join(outDir, "bridge.js"));
const manifest = {
  versions,
  server: serverMetadata,
  wasm: { byteCount: wasmBytes.byteLength, sha256: wasmSHA256 },
  bridge: { byteCount: bridgeStat.size },
};
await writeFile(path.join(outDir, "manifest.json"), JSON.stringify(manifest, null, 2) + "\n");

console.log(`bridge.js  ${(bridgeStat.size / 1024).toFixed(0)} KiB`);
console.log(`server.wasm ${(wasmBytes.byteLength / 1024 / 1024).toFixed(1)} MiB (sha256 ${wasmSHA256.slice(0, 12)}…)`);
console.log(`written to ${path.relative(process.cwd(), outDir)}`);
