package dev.cerbos.epdp

import android.annotation.SuppressLint
import android.content.Context
import android.content.pm.ApplicationInfo
import android.os.Handler
import android.os.Looper
import android.webkit.ConsoleMessage
import android.webkit.JavascriptInterface
import android.webkit.PermissionRequest
import android.webkit.RenderProcessGoneDetail
import android.webkit.WebChromeClient
import android.webkit.WebResourceError
import android.webkit.WebResourceRequest
import android.webkit.WebResourceResponse
import android.webkit.WebSettings
import android.webkit.WebView
import android.webkit.WebViewClient
import androidx.annotation.MainThread
import java.io.ByteArrayInputStream
import java.io.IOException
import java.lang.ref.WeakReference
import kotlin.coroutines.cancellation.CancellationException
import kotlin.time.Duration
import kotlin.time.Duration.Companion.seconds
import kotlinx.coroutines.CompletableDeferred
import kotlinx.coroutines.TimeoutCancellationException
import kotlinx.coroutines.withTimeout

/**
 * Owns the hidden [WebView] that runs `@cerbos/embedded-client` and the Cerbos WebAssembly module.
 *
 * The page, bridge script and `server.wasm` are served from the app's assets by intercepting
 * requests to a private `https` origin, so nothing is fetched from a CDN and Chromium can compile
 * the module with `WebAssembly.compileStreaming`. Calls into the page go through
 * `evaluateJavascript` with JSON-literal arguments and return the bridge's JSON envelope through a
 * `@JavascriptInterface` object; events come back the same way.
 *
 * Everything here runs on the main thread; the JavaScript interface marshals onto it.
 */
@MainThread
internal class CerbosWebViewHost(context: Context) {
    companion object {
        /**
         * A reserved host that never resolves; every request to it is answered from the app's
         * assets.
         */
        const val ORIGIN = "https://appassets.androidplatform.net"
        const val ASSET_DIRECTORY = "cerbos-epdp"
        const val PATH_PREFIX = "/$ASSET_DIRECTORY/"
        const val PAGE_URL = "$ORIGIN${PATH_PREFIX}index.html"
        const val HOST_OBJECT_NAME = "cerbosHost"

        private val files =
            mapOf(
                "index.html" to "text/html",
                "bridge.js" to "text/javascript",
                "server.wasm" to "application/wasm",
                "manifest.json" to "application/json",
            )
        private val requiredFiles = listOf("index.html", "bridge.js", "server.wasm")
    }

    private val appContext: Context = context.applicationContext
    private val mainHandler = Handler(Looper.getMainLooper())

    var onEvent: ((BridgeEvent) -> Unit)? = null
    var onProcessTerminated: (() -> Unit)? = null

    var webView: WebView? = null
        private set

    var isBridgeReady: Boolean = false
        private set

    /** Incremented per page; messages from an older page are ignored. */
    private var generation = 0
    private var readySignal: CompletableDeferred<Unit>? = null
    private val pendingCalls = HashMap<String, CompletableDeferred<String>>()
    private var callCounter = 0L

    /** Checks that the assets generated by `CerbosBridge/build.mjs` are packaged. */
    fun verifyBundledResources(): CerbosException? {
        val present =
            try {
                appContext.assets.list(ASSET_DIRECTORY)?.toSet() ?: emptySet()
            } catch (_: IOException) {
                emptySet()
            }
        val missing = requiredFiles.filterNot { it in present }
        if (missing.isEmpty()) return null
        return CerbosException.WebView(
            "bundled web resources are missing (${missing.joinToString()}); run `npm run build` in CerbosBridge"
        )
    }

    // MARK: Lifecycle

    /**
     * Creates the web view (if needed), loads the bridge page and waits until the bridge script is
     * ready.
     */
    suspend fun start(timeout: Duration = 30.seconds) {
        if (webView != null && isBridgeReady) return
        shutdown()

        val pageGeneration = ++generation
        val webView =
            try {
                WebView(appContext)
            } catch (error: RuntimeException) {
                // No WebView provider installed, or it is being updated.
                throw CerbosException.WebView("WebView is unavailable: ${error.message ?: error}")
            }
        configure(webView, pageGeneration)
        this.webView = webView
        isBridgeReady = false
        val ready = CompletableDeferred<Unit>()
        readySignal = ready

        CerbosLog.info("Loading Cerbos embedded PDP bridge page")
        webView.loadUrl(PAGE_URL)
        try {
            withTimeout(timeout) { ready.await() }
        } catch (_: TimeoutCancellationException) {
            if (readySignal === ready) readySignal = null
            throw CerbosException.Timeout("load the bridge page")
        }
    }

    /** Tears down the web view. [start] builds a fresh one. */
    fun shutdown() {
        failReady(CerbosException.WebView("shut down"))
        failPendingCalls(CerbosException.WebView("shut down"))
        isBridgeReady = false
        val webView = webView ?: return
        this.webView = null
        generation++
        webView.stopLoading()
        webView.webViewClient = WebViewClient()
        webView.webChromeClient = null
        webView.removeJavascriptInterface(HOST_OBJECT_NAME)
        webView.destroy()
    }

    @SuppressLint("SetJavaScriptEnabled")
    private fun configure(webView: WebView, pageGeneration: Int) {
        with(webView.settings) {
            javaScriptEnabled = true
            // The page only ever loads its own bundled resources and talks to Cerbos Hub.
            allowFileAccess = false
            allowContentAccess = false
            domStorageEnabled = false
            javaScriptCanOpenWindowsAutomatically = false
            setSupportMultipleWindows(false)
            setGeolocationEnabled(false)
            mixedContentMode = WebSettings.MIXED_CONTENT_NEVER_ALLOW
            cacheMode = WebSettings.LOAD_NO_CACHE
            blockNetworkImage = true
            loadsImagesAutomatically = false
        }
        if (appContext.applicationInfo.flags and ApplicationInfo.FLAG_DEBUGGABLE != 0) {
            WebView.setWebContentsDebuggingEnabled(true) // chrome://inspect > Cerbos embedded PDP
        }
        webView.addJavascriptInterface(HostObject(this, pageGeneration), HOST_OBJECT_NAME)
        webView.webViewClient = Client(pageGeneration)
        webView.webChromeClient = ChromeClient()
    }

    private fun failReady(error: CerbosException) {
        val ready = readySignal ?: return
        readySignal = null
        ready.completeExceptionally(error)
    }

    private fun failPendingCalls(error: CerbosException) {
        if (pendingCalls.isEmpty()) return
        val calls = pendingCalls.values.toList()
        pendingCalls.clear()
        calls.forEach { it.completeExceptionally(error) }
    }

    // MARK: Calls into the bridge

    /**
     * Invokes a bridge method and returns its JSON envelope. A [timeout] turns a call that never
     * resolves in the page into [CerbosException.Timeout].
     */
    suspend fun call(method: String, paramsJSON: String?, timeout: Duration?): String {
        val webView = webView
        if (webView == null || !isBridgeReady) throw CerbosException.NotReady

        val id = "call-${++callCounter}"
        val deferred = CompletableDeferred<String>()
        pendingCalls[id] = deferred
        val script =
            "try { window.CerbosBridge.invoke(${BridgeJson.jsLiteral(id)}, ${BridgeJson.jsLiteral(method)}, " +
                "${paramsJSON?.let(BridgeJson::jsLiteral) ?: "null"}); \"ok\" } catch (e) { \"error: \" + e }"
        webView.evaluateJavascript(script) { value ->
            // `value` is the JSON-encoded completion value of the script: `"ok"` when the call was
            // dispatched.
            if (value != "\"ok\"") {
                pendingCalls
                    .remove(id)
                    ?.completeExceptionally(
                        CerbosException.WebView(
                            "bridge call could not be dispatched: ${value ?: "no result"}"
                        )
                    )
            }
        }
        try {
            return if (timeout == null) deferred.await()
            else withTimeout(timeout) { deferred.await() }
        } catch (_: TimeoutCancellationException) {
            pendingCalls.remove(id)
            throw CerbosException.Timeout(method)
        } catch (error: CancellationException) {
            pendingCalls.remove(id)
            throw error
        }
    }

    /** Answers a `jwtDecode` request from the bridge. */
    fun resolveCallback(id: String, payloadJSON: String?, errorMessage: String?) {
        val webView = webView ?: return
        val script =
            "window.CerbosBridge.resolveCallback(${BridgeJson.jsLiteral(id)}, ${errorMessage == null}, " +
                "${BridgeJson.jsLiteral(payloadJSON ?: errorMessage ?: "")});"
        webView.evaluateJavascript(script, null)
    }

    // MARK: Messages from the page (main thread)

    private fun receiveEvent(pageGeneration: Int, json: String) {
        if (pageGeneration != generation) return
        val event =
            try {
                BridgeEvent.decode(json)
            } catch (error: CerbosException) {
                CerbosLog.error("Failed to decode bridge event: ${error.message}")
                return
            }
        if (event is BridgeEvent.BridgeReady) {
            isBridgeReady = true
            val ready = readySignal
            readySignal = null
            ready?.complete(Unit)
        }
        onEvent?.invoke(event)
    }

    private fun receiveResult(pageGeneration: Int, id: String, envelopeJSON: String) {
        if (pageGeneration != generation) return
        val pending = pendingCalls.remove(id)
        if (pending == null) {
            CerbosLog.debug(
                "A bridge call completed after its timeout; the late result was discarded"
            )
            return
        }
        pending.complete(envelopeJSON)
    }

    private fun handleRenderProcessGone(pageGeneration: Int, detail: RenderProcessGoneDetail?) {
        if (pageGeneration != generation) return
        val reason =
            if (detail?.didCrash() == true) "renderer process crashed"
            else
                "renderer process was killed by the system (priority ${detail?.rendererPriorityAtExit()})"
        CerbosLog.error("Web view $reason")
        isBridgeReady = false
        failReady(CerbosException.WebView(reason))
        failPendingCalls(CerbosException.WebView(reason))
        // The WebView instance is unusable after its renderer is gone; drop it so the next start()
        // builds a new one.
        webView?.let { dead ->
            webView = null
            generation++
            dead.removeJavascriptInterface(HOST_OBJECT_NAME)
            dead.destroy()
        }
        onProcessTerminated?.invoke()
    }

    /** Injected as `window.cerbosHost`. Chromium calls these on its own thread. */
    private class HostObject(host: CerbosWebViewHost, private val pageGeneration: Int) {
        private val host = WeakReference(host)

        @JavascriptInterface
        fun postMessage(json: String) {
            val host = host.get() ?: return
            host.mainHandler.post { host.receiveEvent(pageGeneration, json) }
        }

        @JavascriptInterface
        fun postResult(id: String, envelopeJSON: String) {
            val host = host.get() ?: return
            host.mainHandler.post { host.receiveResult(pageGeneration, id, envelopeJSON) }
        }
    }

    private inner class Client(private val pageGeneration: Int) : WebViewClient() {
        /** Serves the bundled resources. Runs on a Chromium IO thread. */
        override fun shouldInterceptRequest(
            view: WebView,
            request: WebResourceRequest,
        ): WebResourceResponse? {
            val url = request.url
            if (url.scheme != "https" || "$ORIGIN".removePrefix("https://") != url.host) return null
            val path = url.path ?: return notFound(url.toString())
            if (!path.startsWith(PATH_PREFIX)) return notFound(url.toString())
            val name = path.removePrefix(PATH_PREFIX)
            val mimeType = files[name] ?: return notFound(url.toString())
            val stream =
                try {
                    appContext.assets.open("$ASSET_DIRECTORY/$name")
                } catch (_: IOException) {
                    return notFound(url.toString())
                }
            return WebResourceResponse(
                mimeType,
                null,
                200,
                "OK",
                mapOf("Cache-Control" to "no-store"),
                stream,
            )
        }

        private fun notFound(url: String): WebResourceResponse {
            CerbosLog.error("Bridge resource not found: $url")
            return WebResourceResponse(
                "text/plain",
                "utf-8",
                404,
                "Not Found",
                emptyMap(),
                ByteArrayInputStream(ByteArray(0)),
            )
        }

        /** The page must never navigate anywhere but its own bundled page. */
        override fun shouldOverrideUrlLoading(view: WebView, request: WebResourceRequest): Boolean =
            request.url.toString() != PAGE_URL

        override fun onPageFinished(view: WebView, url: String?) {
            CerbosLog.debug("Bridge page loaded")
        }

        override fun onReceivedError(
            view: WebView,
            request: WebResourceRequest,
            error: WebResourceError,
        ) {
            if (!request.isForMainFrame || pageGeneration != generation) return
            failReady(CerbosException.WebView("${error.description} (${error.errorCode})"))
        }

        override fun onReceivedHttpError(
            view: WebView,
            request: WebResourceRequest,
            errorResponse: WebResourceResponse,
        ) {
            if (!request.isForMainFrame || pageGeneration != generation) return
            failReady(
                CerbosException.WebView("HTTP ${errorResponse.statusCode} loading the bridge page")
            )
        }

        override fun onRenderProcessGone(view: WebView, detail: RenderProcessGoneDetail?): Boolean {
            handleRenderProcessGone(pageGeneration, detail)
            return true
        }
    }

    private class ChromeClient : WebChromeClient() {
        override fun onConsoleMessage(message: ConsoleMessage): Boolean {
            val text = "[bridge console] ${message.message()}"
            when (message.messageLevel()) {
                ConsoleMessage.MessageLevel.ERROR -> CerbosLog.error(text)
                ConsoleMessage.MessageLevel.WARNING -> CerbosLog.warn(text)
                else -> CerbosLog.debug(text)
            }
            return true
        }

        override fun onPermissionRequest(request: PermissionRequest) {
            request.deny()
        }
    }
}
